// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_Gk_ROzfEJsr-aypQb_gOaPaPAyqQl0',
    appId: '1:306385956502:web:8b4e0c7b772b5280239cb7',
    messagingSenderId: '306385956502',
    projectId: 'ticket-booking-ed971',
    authDomain: 'ticket-booking-ed971.firebaseapp.com',
    databaseURL: 'https://ticket-booking-ed971-default-rtdb.firebaseio.com',
    storageBucket: 'ticket-booking-ed971.appspot.com',
    measurementId: 'G-0RNQBHCM3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH0C_NdAOqG-PWGRNnEkeL89pcpM5bD_8',
    appId: '1:306385956502:android:102b1b568ca5a14c239cb7',
    messagingSenderId: '306385956502',
    projectId: 'ticket-booking-ed971',
    databaseURL: 'https://ticket-booking-ed971-default-rtdb.firebaseio.com',
    storageBucket: 'ticket-booking-ed971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_qU_HkhVabqWHppO48dXqGr3OKaoBEME',
    appId: '1:306385956502:ios:fe665908943bceb2239cb7',
    messagingSenderId: '306385956502',
    projectId: 'ticket-booking-ed971',
    databaseURL: 'https://ticket-booking-ed971-default-rtdb.firebaseio.com',
    storageBucket: 'ticket-booking-ed971.appspot.com',
    androidClientId: '306385956502-imlvnatb9mada0jmq7jrbvu61s1mboe9.apps.googleusercontent.com',
    iosClientId: '306385956502-aobqgs9hmlbfpkfmsomn050782phashd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketbooking',
  );
}
